# Generated by Django 3.2.5 on 2022-01-15 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_postimage_image'),
        ('posts', '0002_post_user'),
    ]

    operations = [
    ]
