# Generated by Django 3.2.5 on 2022-01-07 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_post_liked_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='liked_by',
            new_name='likes',
        ),
    ]
