# Generated by Django 3.2.5 on 2022-01-07 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_rename_liked_by_post_likes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postcomment',
            options={'verbose_name': 'Post Comment', 'verbose_name_plural': 'Post Comments'},
        ),
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='dsadsad'),
            preserve_default=False,
        ),
    ]
